name: iOS starter workflow

on:
  push:
    branches: [ "2.0.0" ]
  pull_request:
    branches: [ "2.0.0" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: flutter build ios
        run: flutter build ios
      - name: Upload Runner.app file
        uses: actions/upload-artifact@v4
        with:
          name: Bujuan
          path: build/ios/*.app
